#########################################################################
# Title:         Saltbox: UnionFS | Docker | Container Stop Tasks       #
# Author(s):     desimaniac, salty                                      #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Populate Service Facts
  ansible.builtin.service_facts:

- name: Get Docker service state
  ansible.builtin.set_fact:
    remote_docker_service_running: "{{ (services['docker.service'] is defined) and (services['docker.service']['state'] == 'running') }}"
  when: remote_docker_binary.stat.exists

- name: Tasks for when Docker exists and is running
  when: remote_docker_binary.stat.exists and remote_docker_service_running
  block:
    - name: "Gather list of running Docker containers"
      ansible.builtin.shell: "docker ps --format '{{ '{{' }} .Names{{ '}}' }}' --filter label=com.github.saltbox.saltbox_managed=true | xargs echo -n"
      register: saltbox_managed_containers
      ignore_errors: true

    - name: "Set 'containers_list' variable"
      ansible.builtin.set_fact:
        containers_list: "{{ saltbox_managed_containers.stdout }}"

    - name: "Stop all running Docker containers"
      ansible.builtin.shell: "docker stop {{ containers_list }}"
      ignore_errors: true
      when: (containers_list | trim | length > 0)

    - name: Stop docker service
      ansible.builtin.systemd:
        name: docker
        state: stopped
