#########################################################################
# Title:         Saltbox: Python                                        #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Fail if not running Ubuntu 20.04 when installing Python 3.8"
  ansible.builtin.fail:
    msg: "This role is only for Ubuntu 22.04+ when installing Python 3.8"
  when: ansible_distribution_version is version('20.04', '==') and python_version == "3.8"

- name: "Fail if not running Ubuntu 22.04 when installing Python 3.10"
  ansible.builtin.fail:
    msg: "This role is only for Ubuntu 20.04 and 24.04+ when installing Python 3.10"
  when: ansible_distribution_version is version('22.04', '==') and python_version == "3.10"

- name: "Fail if running Ubuntu 24.04 when installing Python 3.12"
  ansible.builtin.fail:
    msg: "This role is only for Ubuntu 20.04 and 22.04 when installing Python 3.12"
  when: ansible_distribution_version is version('24.04', '==') and python_version == "3.12"

- name: Remove old repository entry
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    filename: "deadsnakes"
    update_cache: true
    state: absent
  loop:
    - "{{ python_apt_repo_url_old }}"
    - "{{ python_apt_repo_url }}"

- name: Add deadsnakes/ppa
  ansible.builtin.shell: add-apt-repository ppa:deadsnakes/ppa --yes
  register: result
  retries: "{{ ansible_retry_count if (not continuous_integration) else ansible_retry_count_ci }}"
  delay: 10
  until: result is succeeded

- name: "Install Python Packages"
  block:
    - name: "Install Python {{ python_version }}"
      ansible.builtin.apt:
        name: "python{{ python_version }}"
        state: present

    - name: "Install Python {{ python_version }} dev"
      ansible.builtin.apt:
        name: "python{{ python_version }}-dev"
        state: present

    - name: "Install Python {{ python_version }} distutils"
      ansible.builtin.apt:
        name: "python{{ python_version }}-distutils"
        state: present

    - name: "Install Python {{ python_version }} venv"
      ansible.builtin.apt:
        name: "python{{ python_version }}-venv"
        state: present

    - name: "Install pip for Python {{ python_version }}"
      ansible.builtin.command: "python{{ python_version }} -m ensurepip"

  rescue:
    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: yes

    - name: "Install Python {{ python_version }}"
      ansible.builtin.apt:
        name: "python{{ python_version }}"
        state: present

    - name: "Install Python {{ python_version }} dev"
      ansible.builtin.apt:
        name: "python{{ python_version }}-dev"
        state: present

    - name: "Install Python {{ python_version }} distutils"
      ansible.builtin.apt:
        name: "python{{ python_version }}-distutils"
        state: present

    - name: "Install Python {{ python_version }} venv"
      ansible.builtin.apt:
        name: "python{{ python_version }}-venv"
        state: present

    - name: "Install pip for Python {{ python_version }}"
      ansible.builtin.command: "python{{ python_version }} -m ensurepip"

- name: Fix System pip
  ansible.builtin.import_tasks: "subtasks/pip.yml"
  when: (not continuous_integration)
