#########################################################################
# Title:         Saltbox: System | sysctl Tasks                         #
# Author(s):     l3uddz, desimaniac, salty                              #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: sysctl | Tuning
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  ignore_errors: true
  loop: "{{ sysctl_settings | dict2items }}"

- name: sysctl | Check to see if '/proc/sys/net/core/netdev_budget_usecs' exists
  ansible.builtin.stat:
    path: "/proc/sys/net/core/netdev_budget_usecs"
  register: netdev_budget_usecs

- name: sysctl | Determine CONFIG_HZ
  ansible.builtin.shell: grep '^CONFIG_HZ=' /boot/config-$(uname -r) | awk -F '=' '{print $2}'
  register: kernel_config_hz
  changed_when: false
  when: netdev_budget_usecs.stat.exists

- name: sysctl | Tuning - 'netdev_budget_usecs'
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  ignore_errors: true
  loop:
    # Set netdev_budget_usecs
    - { name: net.core.netdev_budget_usecs, value: "{{ sysctl_netdev_budget_usecs }}" }
  when: netdev_budget_usecs.stat.exists and (sysctl_netdev_budget_usecs != 5000 or kernel_config_hz.stdout == 1000)

- name: sysctl | Remove old settings
  ansible.posix.sysctl:
    name: "{{ item }}"
    state: absent
    reload: true
  ignore_errors: true
  loop: "{{ sysctl_remove_settings }}"

- name: sysctl | Reload sysctl settings.
  ansible.builtin.shell: sysctl --system
