##########################################################################
# Title:         Saltbox: Authentik | Default Variables                  #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Saltbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

authentik_name: authentik

################################
# Paths
################################

authentik_paths_folder: "{{ authentik_name }}"
authentik_paths_location: "{{ server_appdata_path }}/{{ authentik_paths_folder }}"
authentik_paths_folders_list:
  - "{{ authentik_paths_location }}"
  - "{{ authentik_paths_location }}/media"
  - "{{ authentik_paths_location }}/custom-templates"
  - "{{ authentik_paths_location }}/certs"

################################
# Web
################################

authentik_web_subdomain: "auth"
authentik_web_domain: "{{ user.domain }}"
authentik_web_port: "9000"
authentik_web_url: "{{ 'https://' + (authentik_web_subdomain + '.' + authentik_web_domain
                    if (authentik_web_subdomain | length > 0)
                    else authentik_web_domain) }}"

################################
# DNS
################################

authentik_dns_record: "{{ authentik_web_subdomain }}"
authentik_dns_zone: "{{ authentik_web_domain }}"
authentik_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

authentik_traefik_sso_middleware: ""
authentik_traefik_middleware_default: "{{ traefik_default_middleware }}"
authentik_traefik_middleware_custom: ""
authentik_traefik_certresolver: "{{ traefik_default_certresolver }}"
authentik_traefik_enabled: true
authentik_traefik_api_enabled: false
authentik_traefik_api_endpoint: ""

################################
# Setup
################################

authentik_host: "{{ 'http://127.0.0.1:9000'
                 if continuous_integration
                 else 'http://' + authentik_name + ':9000' }}"
authentik_default_user: "akadmin"

################################
# Docker
################################

# Container
authentik_docker_container: "{{ authentik_name }}"

# Image
authentik_docker_image_pull: true
authentik_docker_image_tag: "2024.2.2"
authentik_docker_image: "ghcr.io/goauthentik/server:{{ authentik_docker_image_tag }}"

# Ports
authentik_docker_ports_defaults: "{{ ['9000:9000/tcp'] if continuous_integration else [] }}"
authentik_docker_ports_custom: []
authentik_docker_ports: "{{ authentik_docker_ports_defaults
                          + authentik_docker_ports_custom }}"

# Envs
authentik_docker_envs_default:
  AUTHENTIK_REDIS__HOST: authentik-redis
  AUTHENTIK_POSTGRESQL__HOST: authentik-postgres
  AUTHENTIK_POSTGRESQL__USER: "{{ postgres_docker_env_user }}"
  AUTHENTIK_POSTGRESQL__NAME: "authentik"
  AUTHENTIK_POSTGRESQL__PASSWORD: "{{ postgres_docker_env_password }}"
  AUTHENTIK_SECRET_KEY: "{{ authentik_saltbox_facts.facts.secret_key }}"
  AUTHENTIK_BOOTSTRAP_TOKEN: "{{ omit if authentik_data_folder.stat.exists else authentik_bootstrap_token }}"
authentik_docker_envs_custom: {}
authentik_docker_envs: "{{ authentik_docker_envs_default
                           | combine(authentik_docker_envs_custom) }}"

# Commands
authentik_docker_commands_default:
  - "server"
authentik_docker_commands_custom: []
authentik_docker_commands: "{{ authentik_docker_commands_default
                               + authentik_docker_commands_custom }}"

# Volumes
authentik_docker_volumes_default:
  - "{{ authentik_paths_location }}/media:/media"
  - "{{ authentik_paths_location }}/custom-templates:/templates"
authentik_docker_volumes_custom: []
authentik_docker_volumes: "{{ authentik_docker_volumes_default
                              + authentik_docker_volumes_custom }}"

# Devices
authentik_docker_devices_default: []
authentik_docker_devices_custom: []
authentik_docker_devices: "{{ authentik_docker_devices_default
                              + authentik_docker_devices_custom }}"

# Hosts
authentik_docker_hosts_default: []
authentik_docker_hosts_custom: []
authentik_docker_hosts: "{{ docker_hosts_common
                            | combine(authentik_docker_hosts_default)
                            | combine(authentik_docker_hosts_custom) }}"

# Labels
authentik_docker_labels_default:
  traefik.http.routers.authentik-outpost.rule: "PathPrefix(`/outpost.goauthentik.io/`)"
  traefik.http.routers.authentik-outpost.priority: "99"
  traefik.http.routers.authentik.service: "authentik-outpost"
  traefik.http.services.authentik-outpost.loadbalancer.server.port: "9000"
authentik_docker_labels_custom: {}
authentik_docker_labels: "{{ docker_labels_common
                             | combine(authentik_docker_labels_default)
                             | combine(authentik_docker_labels_custom) }}"

# Hostname
authentik_docker_hostname: "{{ authentik_name }}"

# Networks
authentik_docker_networks_alias: "{{ authentik_name }}"
authentik_docker_networks_default: []
authentik_docker_networks_custom: []
authentik_docker_networks: "{{ docker_networks_common
                               + authentik_docker_networks_default
                               + authentik_docker_networks_custom }}"

# Capabilities
authentik_docker_capabilities_default: []
authentik_docker_capabilities_custom: []
authentik_docker_capabilities: "{{ authentik_docker_capabilities_default
                                   + authentik_docker_capabilities_custom }}"

# Security Opts
authentik_docker_security_opts_default: []
authentik_docker_security_opts_custom: []
authentik_docker_security_opts: "{{ authentik_docker_security_opts_default
                                    + authentik_docker_security_opts_custom }}"

# Restart Policy
authentik_docker_restart_policy: unless-stopped

# State
authentik_docker_state: started

# Dependencies
authentik_depends_on: "authentik-redis,authentik-postgres"
authentik_depends_on_delay: "0"
authentik_depends_on_healthchecks: "false"
