#########################################################################
# Title:         Saltbox: Docker | Daemon Tasks                         #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Daemon | Create docker directory"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0775"
    owner: root
    group: root
  with_items:
    - /etc/docker

- name: "Daemon | Import 'daemon.json'"
  ansible.builtin.template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: "0664"
    force: true

- name: "Daemon | Create override directory"
  ansible.builtin.file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: "0644"

- name: "Daemon | Import override file"
  ansible.builtin.template:
    src: override.conf.j2
    dest: /etc/systemd/system/docker.service.d/override.conf
    mode: "0644"
    force: "{{ docker_service_force }}"

- name: "Daemon | Remove old init entry from '/etc/docker/daemon.json'"
  ansible.builtin.shell: jq 'del(."init")' /etc/docker/daemon.json | sponge /etc/docker/daemon.json
