#########################################################################
# Title:         Saltbox: Cloudflare | Configuration Rules Task         #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
# Delete any existing CF Configuration Rules for Lets Encrypt

- name: Configuration Rules | Remove Configuration Rule Task
  ansible.builtin.import_tasks: "configuration_rules/remove_configuration_rule.yml"
  when: (cloudflare_rule_ids | length > 0)

# Create new CF Configuration Rule for Lets Encrypt

- name: Configuration Rules | Add Configuration Rule Task
  ansible.builtin.import_tasks: "configuration_rules/add_configuration_rule.yml"
