#########################################################################
# Title:         Saltbox: Cloudflare | Variables Task                   #
# Author(s):     desimaniac, salty                                      #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Variables | Set 'saltbox_type' variable
  ansible.builtin.set_fact:
    saltbox_type: "{{ 'saltbox' if ('saltbox' in ansible_run_tags)
      else 'mediabox' if ('mediabox' in ansible_run_tags)
      else 'feederbox' if ('feederbox' in ansible_run_tags)
      else '' }}"

- name: Get FLD
  ansible.builtin.shell: |
    {{ saltbox_python }} -c "from tld import get_tld; res = get_tld(\"http://{{ dns_zone | default(user.domain) }}\", as_object=True); print(res.fld)"
  register: fld

- name: Variables | Fetch Cloudflare Zones
  ansible.builtin.uri:
    url: 'https://api.cloudflare.com/client/v4/zones?name={{ fld.stdout }}'
    method: 'GET'
    headers:
      Content-Type: "application/json"
      X-Auth-Email: '{{ cloudflare.email }}'
      X-Auth-Key: '{{ cloudflare.api }}'
    return_content: true
  register: cf_zones

- name: Variables | Set 'cloudflare_zone' Variable
  ansible.builtin.set_fact:
    cloudflare_zone: "{{ cf_zones.json.result[0].id }}"

- name: Variables | Fetch Cloudflare Rulesets
  ansible.builtin.uri:
    url: "https://api.cloudflare.com/client/v4/zones/{{ cloudflare_zone }}/rulesets/phases/http_config_settings/entrypoint"
    method: GET
    headers:
      X-Auth-Email: "{{ cloudflare.email }}"
      X-Auth-Key: "{{ cloudflare.api }}"
      Content-Type: "application/json"
  register: cf_rules_response

- name: Variables | Extract Ruleset ID and Rule IDs
  ansible.builtin.set_fact:
    cloudflare_ruleset_id: "{{ cf_rules_response.json.result.id }}"
    cloudflare_rule_ids: >-
      {{
        cf_rules_response.json.result.rules
        | selectattr('expression', 'search', 'http\.request\.uri\.path contains "/.well-known/acme-challenge"')
        | map(attribute='id')
        | list
      }}
