#########################################################################
# Title:         Saltbox: Mainline Role                                 #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Install gnupg Dependencies
  ansible.builtin.apt:
    name: dirmngr

- name: Remove old repository entry
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/cappelikan.gpg] http://ppa.launchpad.net/cappelikan/ppa/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main"
    filename: "cappelikan"
    update_cache: true
    state: absent
  loop:
    - "deb [arch=amd64 signed-by=/usr/share/keyrings/cappelikan.gpg] http://ppa.launchpad.net/cappelikan/ppa/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main"
    - "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/cappelikan.asc] http://ppa.launchpad.net/cappelikan/ppa/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main"

- name: Add deadsnakes/ppa
  ansible.builtin.shell: add-apt-repository ppa:cappelikan/ppa --yes
  register: result
  retries: "{{ ansible_retry_count if (not continuous_integration) else ansible_retry_count_ci }}"
  delay: 10
  until: result is succeeded

- name: Install mainline
  ansible.builtin.apt:
    name: mainline
    state: latest
